### ISSUE TITLE
allow multiple types in `add_file()` or add documentation about type manipulation

### ISSUE THREAD

**Issue by mashehu** [ResearchObject/ro-crate-py#174]
According to the "Main Workflow Diagram" section in https://about.workflowhub.eu/Workflow-RO-Crate/ the workflow diagram should have types `["File", "ImageObject"]`, however using `add_file()` automatically assigns only type `File`. 

Is there a way how I can add this additional type either during `add_file()` or afterwards?

**Comment by simleo** [comment]
```python
diagram = crate.add_file("diagram.png", properties={"@type": ["File", "ImageObject"]})
```
