### ISSUE TITLE
Release ro-crate-py 0.10.0?

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate-py#177]
@elichad pointed out we should do a new release, is there anything in flux before we push the button?

This would be it seems a new minor release, as it's adding the new CLI commands for `file` `dataset`  (#171 by @simleo) 

Or are we ready to call it `1.0.0` ..?

**Comment by stain** [comment]
As pointed out in #175, adding #173 as well to this release.

**Comment by simleo** [comment]
I would name it 0.10.0 and yes, include #173 (which is waiting for author / copyright info from the new contributors).

**Comment by simleo** [comment]
Done
