### ISSUE TITLE
FEATURE: Load a crate from a (json) Object 

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate-py#178]
Unless I misunderstand this library can only read crates from disk. It would be very useful to be able to instantiate the library with an object (that would serialise in JSON to an RO-Crate Metadata Document).  Eg if I have fetched RO-Crate metadata from an API.

**Comment by simleo** [comment]
You mean a Python dictionary, I guess. It would be able to point only to web-based data entities

**Comment by ptsefton** [comment]
It can point to *anything* as an abstract structure including file paths -- but these not exist for some purposes eg writing a validator that might run in a context other than the place where the files are.

But yes, with an API at the moment if you fetch an RO-Crate metadata document it has to be saved before the library can use it, which is not optimal -- loading raw JSON  or a python dictionary structure would be preferable.

**Comment by simleo** [comment]
Implemented in #183. The metadata can point to nonexistent files or directories, the behavior when writing the crate is described in #136.

**Comment by ptsefton** [comment]
Thanks @simleo - this does not appear to be released yet -- would love to use it

**Comment by simleo** [comment]
I have just released version 0.11.0
