### ISSUE TITLE
Failure to load ro-crates from eln file format due to missing @id

### ISSUE THREAD

**Issue by salexan2001** [ResearchObject/ro-crate-py#202]
I am currently working on implementing support for the [eln file](https://github.com/TheELNConsortium/TheELNFileFormat) format into [LinkAhead](https://gitlab.com/linkahead/). As the eln file format is supposed to be based on/compatible to the RO-Crate specification, I'd like to re-use this package to load eln-files.

The ELNFileFormat repository provides some example files (e.g. https://github.com/TheELNConsortium/TheELNFileFormat/tree/master/examples/PASTA) which I am trying to load now using the rocrate python package.

For the PASTA.eln example I am receiving errors about missing `@id`s (see below). I was wondering: Are these ids really mandatory? Where in the specs can I find this requirement?

Furthermore, I used the [rocrate-validator](https://github.com/crs4/rocrate-validator) to validate the PASTA.eln file which does not report the above problem with the `@id`s.

My current workaround to this issue is to patch `rocrate/model/entity.py` to auto-generate missing ids in getters and setters of `Entity`.

----------

Error message by rocrate:
```
ValueError: no @id in {'value': 'Test if everything is working as intended.', 'propertyID': '.objective', 'name': ' → Objective', '@type': 'PropertyValue', 'description': 'What is the objective?'}
```

Related excerpt from the PASTA example:
```json
"variableMeasured": [
        {
          "value": "Test if everything is working as intended.",
          "propertyID": ".objective",
          "name": " \u2192 Objective",
          "@type": "PropertyValue",
          "description": "What is the objective?"
        },
        {
          "value": "active",
          "propertyID": ".status",
          "name": " \u2192 Status",
          "@type": "PropertyValue",
          "description": "What is the project status"
        }
      ],
```

**Comment by elichad** [comment]
These entities should not be nested under `variableMeasured` and instead should be listed under `@graph` with their own `@id` - this is why ro-crate-py is failing. RO-Crate requires the JSON-LD to be flattened, but the validator doesn't currently check for this, my colleagues also noticed this and raised an issue about it yesterday: https://github.com/crs4/rocrate-validator/issues/27

From the [Structure](https://www.researchobject.org/ro-crate/specification/1.1/structure.html#ro-crate-metadata-file-ro-crate-metadatajson) page in the RO-Crate spec:
> The RO-Crate Metadata File MUST contain RO-Crate JSON-LD; a valid [JSON-LD 1.0](https://www.w3.org/TR/2014/REC-json-ld-20140116/) document in [flattened](https://www.w3.org/TR/json-ld/#flattened-document-form) and [compacted](https://www.w3.org/TR/json-ld/#compacted-document-form) form

More verbosely, from the [appendix on JSON-LD](https://www.researchobject.org/ro-crate/specification/1.1/appendix/jsonld.html#describing-entities-in-json-ld):
>Because the RO-Crate JSON-LD is flattened, all described entities must be JSON objects as direct children of the @graph element rather than being nested under another object or array. Properties referencing entities must use a JSON object with @id as the only key, e.g. "author": {"@id": "https://orcid.org/0000-0002-1825-0097"}

**Comment by salexan2001** [comment]
Thanks for pointing that out!
