### ISSUE TITLE
"#" prepended automatically to ids of contextual entities

### ISSUE THREAD

**Issue by salexan2001** [ResearchObject/ro-crate-py#203]
While working with the same [example data](https://github.com/TheELNConsortium/TheELNFileFormat/tree/master/examples/PASTA) as in #202 I noticed that ro-crate-py automatically prepends "#" to the `@id`s of contextual entities.

E.g. the `@id` of:
```
    {
      "@id": "PASTA-ELN",
      "@type": "Organization",
      "name": "PASTA ELN",
      "logo": "https://raw.githubusercontent.com/PASTA-ELN/desktop/main/pasta.png",
      "slogan": "The favorite ELN for experimental scientists",
      "url": "https://github.com/PASTA-ELN/",
      "description": "Version 2.6.0"
    }
```
is automatically translated to `#PASTA-ELN`.

Unfortunately this translation is **not** applied to linking properties, e.g.:
```
{'@id': 'ro-crate-metadata.json',
 '@type': 'CreativeWork',
 'conformsTo': {'@id': 'https://w3id.org/ro/crate/1.1'},
 'about': {'@id': './'},
 'schemaVersion': 'v1.0',
 'version': '1.0',
 'datePublished': '2024-10-14T14:10:19.875806',
 'dateCreated': '2024-10-14T14:10:19.875848',
 'sdPublisher': {'@id': 'PASTA-ELN'}}
```
Here, the "sdPublisher" property that is supposed to link to the entity shown above has the value `PASTA_ELN`.

This behavior makes it impossible to reliably use `dereference` on values, because links to contextual entities might be broken.

From https://www.researchobject.org/ro-crate/specification/1.1/appendix/jsonld#describing-entities-in-json-ld I interpret that adding "#" in front of local identifiers is recommended, but not mandatory, so I don't see the necessity of automatically prepending it and possibly breaking internal references. (But I might be mistaken. In this case I would be thankful for pointing me to the respective requirement in the specification.)

**Comment by simleo** [comment]
From the [1.2-DRAFT spec](https://www.researchobject.org/ro-crate/specification/1.2-DRAFT/appendix/jsonld#describing-entities-in-json-ld) it is perhaps even clearer that ids starting with `#` are not required. Indeed, for some entities it recommends blank node identifiers, which start with `_:`. See also https://github.com/ResearchObject/ro-crate/issues/200, which is leveraged by [runcrate](https://github.com/ResearchObject/runcrate).
