### ISSUE TITLE
Set the `encoding` option of the `open()` functions in the codes

### ISSUE THREAD

**Issue by Surpris** [ResearchObject/ro-crate-py#207]
Thank you for developing this excellent library :-)
I have an idea about improving this library, which might be trivial but useful for users.

According to [PEP 597](https://peps.python.org/pep-0597/), it is recommended that Python users set the `encoding` option when using the `open()` function for Python >=3.10.
I think it is better to set the `encoding='utf-8'` options to the `open()` functions in the RO-Crate codes to avoid unexpected errors.
I'll revise the corresponding lines if you agree with this idea.

Thanks in advance and I look forward to hearing from one of the main developers!

**Comment by simleo** [comment]
> I'll revise the corresponding lines if you agree with this idea.

Ok, open a PR

**Comment by Surpris** [comment]
@simleo ,

Thank you for getting back to me.
I opened a pull request for this issue.
I'm sorry to bother you, but could you please check it?
