### ISSUE TITLE
let us provide a pleasant inroad for new contributors

### ISSUE THREAD

**Issue by marc-portier** [ResearchObject/ro-crate-py#56]
- some Contributors.md - readme targetted for people who want to add 
  - listing rules of engagement and the way we work over here
- possibly also adding a (more language independent) Makefile

I suggest we use this issue to gather topical suggestions for those:
- list the commands you all using regularly to build / test / generate docs / linting / ...
- any other suggestions people should be following before suggesting pull requests
- ...

and then use that to actually build those docs and (where possible) automating stuff --> makefile and/or scripts

**Comment by simleo** [comment]
Done in #59
