### ISSUE TITLE
Delete entity support

### ISSUE THREAD

**Issue by cedricdcc** [ResearchObject/ro-crate-py#62]
Right now RO-Crate py is a one way for putting in data.
Scientists will also want to use this tool for managing their data.
This means that putting in a delete function would be useful.
Another interesting enhancement would be the ability to replace certain files.
Say you have a spreadsheet that you have linked a few attributes to and you want to replace this one with an updated spreadsheet.
It would be handy for the user, in this case, to be able to just replace the old file in the RO-Crate with the new one and keep all the attribute metadata of the old file to save time.

**Comment by simleo** [comment]
Yes, it would be pretty useful. In fact, I've been thinking about adding this feature several times, but it turns out it's far from trivial. The thing is that RO-Crate entities (including files and directories) can reference each other, so a contract must be in place to establish what happens to related entities.

For instance, suppose that `A` references `B` which, in turn, references `C`. What happens when you delete `B`? With the current semantics, updating `A` is probably not a big deal: `A`'s property that references `B` can simply return `None`. How to deal with `C` is a different matter. Should it:

* be left dangling (analogy with broken symlinks in file systems)?
* be deleted as well?
  * trigger the recursive deletion of all downstream entities?
  * what if there's a cycle (is a cycle even legal / possible in RO-Crate)?

This needs some careful thought. In any event, triggering the deletion of referenced entities could be made optional to suit different client needs.

**Comment by cedricdcc** [comment]
In my opinion it should trigger a cascade that not deletes the file but a delinkage of the metadata linked to the file.

eg: in your example you would delete  or replace `B` that would first delink all the references it has with `A` and `C` and any other files.

You will be left with some clutter in your ROCrate initially but this can be resolved later by adding a function that checks for files with no links to other files and then deletes them. This solves the problem for your example but for longer pipelines, it can still be a problem to single out the files that need to be deleted.

my solution for this would be:

-  adding pipeline visibility to the ROCrate eg: the ability for a user to see which links there are between files for instance (you can have pipeline `A` -> `B` -> `C` and pipeline `D` -> `E` -> `F` -> `G`) with the latest pipeline being the one with the latest data.
   - a  `show_pipelines` function would track and show all the pipelines
   - a  `delete_pipeline` function with a given entity from that pipeline would then delete all the files linked recursively to this entity and thus the whole pipeline.

In this way, you can solve the provenance and integrity problem that some datasets have and give the user the freedom to add, replace, remove files in the ROCrate without them fearing to delete all the work they have done and giving them the chance to look back at previous iterations of the pipelines they have done.

**Comment by simleo** [comment]
> In my opinion it should trigger a cascade that not deletes the file but a delinkage of the metadata linked to the file.

The issues I pointed out hold for RO-Crate entities in general, not just for data entities (`File` and `Dataset`). Note that I've changed the issue's title accordingly. For `File` entities, there's the *additional* issue of what to do with the corresponding file on the file system. For `Dataset` entities, there's the *additional* (on top of `File` issues :cold_sweat:) issue of what to do with files contained by the corresponding directory on the file system.

> You will be left with some clutter in your ROCrate initially but this can be resolved later by adding a function that checks for files with no links to other files and then deletes them

Also something I've considered in the past (sort of an RO-Crate specific garbage collection), and probably the best option.

> In this way, you can solve the provenance and integrity problem that some datasets have and give the user the freedom to add, replace, remove files in the ROCrate without them fearing to delete all the work they have done and giving them the chance to look back at previous iterations of the pipelines they have done.

Agree on the fact that it's good to provide flexibility to the user. The main thing to watch out for is possible API bloating as more methods and optional parameters are added to the API (though this should be addressable by choosing sensible defaults).

**Comment by marc-portier** [comment]
> Agree on the fact that it's good to provide flexibility to the user. The main thing to watch out for is possible API bloating as more methods and optional parameters are added (though this should be addressable by choosing sensible defaults).

Maybe this can be handled through providing an optional call-back function to the `delete(entities, cleanup_call_back_fn)`  which then offers back lists of dependents and dependencies to be handled (by the user of the API, who is best placed to assess intent and required outcome: e.g. allowing temporary broken dependency chains during a bigger operation that will fix them again).  So the do-nothing default would be ok for me.  
(Alternatively a yield construct leading to `with delete(entities) as dependents, dependencies:`  could work as well, as well as a completely separate call to `check_and_fix_entity_interdependencies(callback)`  

I do like the ideas about dependency checking or even cleanup (garbage collection) but those do start sounding like consistency checking and (even?) validation which are best kept in separate layers? Not mixed, but added onto the strict support of read-write & formatting layer?

On a more practical note:
- is there already any tracking or detection of such dependents and dependencies?
- could we be so bold as to already add the extra signature methods for delete / replace already in the API, possibly leaving them with failing "todo-implement"  messages on the various types of entities?

**Comment by simleo** [comment]
> is there already any tracking or detection of such dependents and dependencies

No, not explicitly. I think it can already be done on the client side, if needed: one could grab the whole entity list and follow the various properties to build the dependency graph.

> could we be so bold as to already add the extra signature methods for delete / replace already in the API, possibly leaving them with failing "todo-implement" messages on the various types of entities?

I too believe in the "got to start somewhere" approach to tackle complex problems :grin: ro-crate-py is still in the `0.x` stage, so we can even afford the luxury of breaking things if need be. In this case we're adding a new feature we can treat as "experimental" (well, more experimental than the other ones), and reserve the right to change its behavior if it's not working properly. Some of the stuff proposed here seems pretty complex though! I think we should start somewhere, but start with simple stuff and build up from there. More concisely and concretely:

* Avoid doing delete and replace at the same time. Replacing is a different feature with different (possibly additional) problems. Let's focus only on deleting for now
* Start by simply deleting and leaving referred entities dangling. The method could return a list of dangling objects to the caller and let it decide what to do with them

I will draft this on a branch and let you guys know, so you can play with it and give feedback.

**Comment by cedricdcc** [comment]
I would be happy to share my code on this.
There is already a rough implementation that can delete files from RO-Crate in this fork. https://github.com/cedricdcc/ro-crate-py

Perhaps we can make a branch with the name delete-file-support?

**Comment by simleo** [comment]
> There is already a rough implementation that can delete files from RO-Crate in this fork. https://github.com/cedricdcc/ro-crate-py

Thanks for the effort @cedricdcc! I looked at your code. Some things could be implemented in a simpler way, while others had to be changed (e.g., you can't delete the root dataset, since it represents the crate itself), so I just went ahead and rolled out my own implementation. This is currently open as a draft pull request in #65.

All: please check it out and provide feedback. Thanks!

P.S.: Looking back at the code, I think replacing is already allowed, though not explicitly supported (again, need to check / document / possibly change what happens to the references).

**Comment by simleo** [comment]
@cedricdcc (and anyone that's interested in contributing): I recently wrote a [short contributing guide](../blob/master/CONTRIBUTING.md), please check it out. For instance, new features should come together with new unit tests that exercise them, and code has to pass linting with `flake8`. Also, remember to delete debugging code such as calls to `print` before committing.

**Comment by simleo** [comment]
Initial implementation added with #65. Any further refinements can come with future PRs.
