### ISSUE TITLE
How do I ...

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate-py#72]
Some documentation I could not find.

How to:

- Iterate over all the items in a crate's graph? It's crude but in the javacript library it's `for (let item crate.getGraph()) { ... }`
- Add a custom item that is not a Person etc that I have constructed myself in JSON (in the Javascript library we say `crate.addItem({"@id": "#someid", "@type": ["CorpusItem", "RepositoryObject"], "name": ....})`
- Fetch an item by @id in js:`crate.getItem("#someid")
- Example task: Add an array of references to RepositoryObjects to the root dataset using a hasMember property and add the Repository Objects to the graph

**Comment by simleo** [comment]
> Some documentation I could not find.
> 
> How to:
> 
> * Iterate over all the items in a crate's graph? It's crude but in the javacript library it's `for (let item crate.getGraph()) { ... }`

```python
from rocrate.rocrate import ROCrate
crate = ROCrate("./")  # assuming crate dir is CWD
for e in crate.get_entities():
    print(f"{e.id}, (e.type)")  # id and type
    print(e.as_jsonld())  # JSON entry
```

> * Add a custom item that is not a Person etc that I have constructed myself in JSON (in the Javascript library we say `crate.addItem({"@id": "#someid", "@type": ["CorpusItem", "RepositoryObject"], "name": ....})`

```python
from rocrate.model.contextentity import ContextEntity
# from the RO-Crate docs
obj = {
    "@id": "https://omeka.uws.edu.au/farmstofreeways/api/items/166",
    "@type": ["RepositoryObject", "Text"],
    "title": "Western Sydney Women's Oral History Project: Flier (illustrated)"
}
flier = crate.add(ContextEntity(crate, identifier=identifier, properties=obj))
```

> * Fetch an item by @id in js:`crate.getItem("#someid")

I'm afraid we don't have this in the public API at the moment. It's something we should add. Since this is Python though, you can easily get it with the classic hack:

```python
>>> r = crate._ROCrate__entity_map["https://omeka.uws.edu.au/farmstofreeways/api/items/166"]
>>> r is flier
True
```

> * Example task: Add an array of references to RepositoryObjects to the root dataset using a hasMember property and add the Repository Objects to the graph

We're using "mentions" to link context entities directly to the root dataset, see #55 (and https://github.com/ResearchObject/ro-crate/issues/122 on which it is based). Anyway, this would work the same for any other root dataset property, 

This is a bit tricky due to the "fancy" get/set item overload in entities:

```python
crate = ROCrate("ro-crate-galaxy-sortchangecase")
json = [
    {
        "@id": "https://example.com/ro/1",
        "@type": "RepositoryObject",
        "title": "RO 1"
    },
    {
        "@id": "https://example.com/ro/2",
        "@type": "RepositoryObject",
        "title": "RO 2"
    },
]
mentions = set(crate.root_dataset["mentions"] or [])
for j in json:
    mentions.add(crate.add(ContextEntity(crate, identifier=j["@id"], properties=j)))
crate.root_dataset["mentions"] = list(mentions)
```

I'm going to keep this open for now, since we should open some "todo" issues stemming from the above considerations before closing.

**Comment by ptsefton** [comment]
Thanks @simleo this is really useful.

I don't understand how to use the `r = crate._ROCrate__entity_map` hack ; if I try it on the example I added in  #77 get an entity map that looks like this:



```
print (crate._ROCrate__entity_map)

{'arcp://uuid,accb7567-49e9-4ce8-bab4-f4876fc89160/ro-crate-metadata.json': <ro-crate-metadata.json CreativeWork>, 'arcp://uuid,accb7567-49e9-4ce8-bab4-f4876fc89160': <./ Dataset>, 'arcp://uuid,accb7567-49e9-4ce8-bab4-f4876fc89160/#collection': <#collection RepositoryCollection >, 'arcp://uuid,accb7567-49e9-4ce8-bab4-f4876fc89160/#./test.csv': <#./test.csv File>}

```

**Comment by ptsefton** [comment]
Actually the equivalent to crate.getId() is crate.dereference - eg:

e = crate.dereference('#files/460/original_49a4d796174100b7f2d2b7529b51e79b.csv')

**Comment by dgarijo** [comment]
It would be great to have some of these tips in the documentation. I have a student that almost discarded using this package because he could  not find the right documentation for accessing the elements of an RO-Crate and their metadata :)

**Comment by simleo** [comment]
> It would be great to have some of these tips in the documentation.

Done in #121
